name: Deploy on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Pakai runner kamu sendiri, bukan github-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     
